// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/daemon/v1/wallet.proto

package daemonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusRequest is empty - no parameters needed.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{0}
}

// StatusResponse contains daemon status information.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the daemon is running (always true if you get a response).
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// Whether the keystore is unlocked.
	Unlocked bool `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	// Number of keys available (only if unlocked).
	KeyCount int32 `protobuf:"varint,3,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"`
	// Seconds until automatic lock (only if unlocked).
	TimeoutRemaining int32 `protobuf:"varint,4,opt,name=timeout_remaining,json=timeoutRemaining,proto3" json:"timeout_remaining,omitempty"`
	// Active tenant ID if set.
	TenantId      string `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *StatusResponse) GetKeyCount() int32 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *StatusResponse) GetTimeoutRemaining() int32 {
	if x != nil {
		return x.TimeoutRemaining
	}
	return 0
}

func (x *StatusResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// UnlockWithPRFRequest contains PRF unlock parameters.
type UnlockWithPRFRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RP ID for WebAuthn (typically the tenant domain).
	RpId string `protobuf:"bytes,1,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	// Credential ID to use for PRF.
	CredentialId []byte `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// Optional user display name for authenticator prompt.
	UserDisplayName string `protobuf:"bytes,3,opt,name=user_display_name,json=userDisplayName,proto3" json:"user_display_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnlockWithPRFRequest) Reset() {
	*x = UnlockWithPRFRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockWithPRFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockWithPRFRequest) ProtoMessage() {}

func (x *UnlockWithPRFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockWithPRFRequest.ProtoReflect.Descriptor instead.
func (*UnlockWithPRFRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *UnlockWithPRFRequest) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *UnlockWithPRFRequest) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *UnlockWithPRFRequest) GetUserDisplayName() string {
	if x != nil {
		return x.UserDisplayName
	}
	return ""
}

// UnlockWithPasswordRequest contains password unlock parameters.
type UnlockWithPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Password to unlock the keystore.
	Password      string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockWithPasswordRequest) Reset() {
	*x = UnlockWithPasswordRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockWithPasswordRequest) ProtoMessage() {}

func (x *UnlockWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*UnlockWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *UnlockWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UnlockResponse is returned after unlock attempts.
type UnlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether unlock was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if unsuccessful.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LockRequest is empty - no parameters needed.
type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{5}
}

// LockResponse is returned after lock.
type LockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether lock was successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *LockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SignJWTRequest contains JWT signing parameters.
type SignJWTRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key ID to use for signing.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// JWT claims as JSON.
	ClaimsJson []byte `protobuf:"bytes,2,opt,name=claims_json,json=claimsJson,proto3" json:"claims_json,omitempty"`
	// Optional JWT headers to include.
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignJWTRequest) Reset() {
	*x = SignJWTRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignJWTRequest) ProtoMessage() {}

func (x *SignJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignJWTRequest.ProtoReflect.Descriptor instead.
func (*SignJWTRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *SignJWTRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignJWTRequest) GetClaimsJson() []byte {
	if x != nil {
		return x.ClaimsJson
	}
	return nil
}

func (x *SignJWTRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// SignJWTResponse contains the signed JWT.
type SignJWTResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed JWT.
	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	// Error message if signing failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignJWTResponse) Reset() {
	*x = SignJWTResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignJWTResponse) ProtoMessage() {}

func (x *SignJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignJWTResponse.ProtoReflect.Descriptor instead.
func (*SignJWTResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *SignJWTResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *SignJWTResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SignRequest contains raw signing parameters.
type SignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key ID to use for signing.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Data to sign (typically a hash).
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// SignResponse contains the signature.
type SignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signature (DER-encoded for ECDSA).
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Error message if signing failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListKeysRequest is empty - no parameters needed.
type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{11}
}

// KeyInfo describes a key in the keystore.
type KeyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key identifier.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Key algorithm (e.g., "ES256").
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Whether key is PRF-protected.
	PrfProtected bool `protobuf:"varint,3,opt,name=prf_protected,json=prfProtected,proto3" json:"prf_protected,omitempty"`
	// Optional credential ID if PRF-protected.
	CredentialId []byte `protobuf:"bytes,4,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// Creation timestamp (Unix seconds).
	CreatedAt     int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *KeyInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyInfo) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *KeyInfo) GetPrfProtected() bool {
	if x != nil {
		return x.PrfProtected
	}
	return false
}

func (x *KeyInfo) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *KeyInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ListKeysResponse contains available keys.
type ListKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of key information.
	Keys          []*KeyInfo `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *ListKeysResponse) GetKeys() []*KeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

// GetApprovalRequest asks for user approval of an operation.
type GetApprovalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of operation requiring approval.
	OperationType string `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// Human-readable description of the operation.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Timeout in seconds before auto-deny.
	TimeoutSeconds int32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Optional additional context as JSON.
	ContextJson   []byte `protobuf:"bytes,4,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApprovalRequest) Reset() {
	*x = GetApprovalRequest{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalRequest) ProtoMessage() {}

func (x *GetApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalRequest.ProtoReflect.Descriptor instead.
func (*GetApprovalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *GetApprovalRequest) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GetApprovalRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetApprovalRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *GetApprovalRequest) GetContextJson() []byte {
	if x != nil {
		return x.ContextJson
	}
	return nil
}

// GetApprovalResponse contains the approval result.
type GetApprovalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation was approved.
	Approved bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	// Whether the request timed out.
	TimedOut bool `protobuf:"varint,2,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	// Error message if approval failed.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApprovalResponse) Reset() {
	*x = GetApprovalResponse{}
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalResponse) ProtoMessage() {}

func (x *GetApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_v1_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalResponse.ProtoReflect.Descriptor instead.
func (*GetApprovalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_v1_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *GetApprovalResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *GetApprovalResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *GetApprovalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_daemon_v1_wallet_proto protoreflect.FileDescriptor

const file_api_proto_daemon_v1_wallet_proto_rawDesc = "" +
	"\n" +
	" api/proto/daemon/v1/wallet.proto\x12\x0fsiros.daemon.v1\"\x0f\n" +
	"\rStatusRequest\"\xad\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1a\n" +
	"\bunlocked\x18\x02 \x01(\bR\bunlocked\x12\x1b\n" +
	"\tkey_count\x18\x03 \x01(\x05R\bkeyCount\x12+\n" +
	"\x11timeout_remaining\x18\x04 \x01(\x05R\x10timeoutRemaining\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"|\n" +
	"\x14UnlockWithPRFRequest\x12\x13\n" +
	"\x05rp_id\x18\x01 \x01(\tR\x04rpId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\fR\fcredentialId\x12*\n" +
	"\x11user_display_name\x18\x03 \x01(\tR\x0fuserDisplayName\"7\n" +
	"\x19UnlockWithPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"@\n" +
	"\x0eUnlockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\r\n" +
	"\vLockRequest\"(\n" +
	"\fLockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\x0eSignJWTRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vclaims_json\x18\x02 \x01(\fR\n" +
	"claimsJson\x12F\n" +
	"\aheaders\x18\x03 \x03(\v2,.siros.daemon.v1.SignJWTRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0fSignJWTResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\vSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fListKeysRequest\"\xa7\x01\n" +
	"\aKeyInfo\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12#\n" +
	"\rprf_protected\x18\x03 \x01(\bR\fprfProtected\x12#\n" +
	"\rcredential_id\x18\x04 \x01(\fR\fcredentialId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"@\n" +
	"\x10ListKeysResponse\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.siros.daemon.v1.KeyInfoR\x04keys\"\xa9\x01\n" +
	"\x12GetApprovalRequest\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fcontext_json\x18\x04 \x01(\fR\vcontextJson\"d\n" +
	"\x13GetApprovalResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1b\n" +
	"\ttimed_out\x18\x02 \x01(\bR\btimedOut\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x98\x05\n" +
	"\fWalletDaemon\x12I\n" +
	"\x06Status\x12\x1e.siros.daemon.v1.StatusRequest\x1a\x1f.siros.daemon.v1.StatusResponse\x12W\n" +
	"\rUnlockWithPRF\x12%.siros.daemon.v1.UnlockWithPRFRequest\x1a\x1f.siros.daemon.v1.UnlockResponse\x12a\n" +
	"\x12UnlockWithPassword\x12*.siros.daemon.v1.UnlockWithPasswordRequest\x1a\x1f.siros.daemon.v1.UnlockResponse\x12C\n" +
	"\x04Lock\x12\x1c.siros.daemon.v1.LockRequest\x1a\x1d.siros.daemon.v1.LockResponse\x12L\n" +
	"\aSignJWT\x12\x1f.siros.daemon.v1.SignJWTRequest\x1a .siros.daemon.v1.SignJWTResponse\x12C\n" +
	"\x04Sign\x12\x1c.siros.daemon.v1.SignRequest\x1a\x1d.siros.daemon.v1.SignResponse\x12O\n" +
	"\bListKeys\x12 .siros.daemon.v1.ListKeysRequest\x1a!.siros.daemon.v1.ListKeysResponse\x12X\n" +
	"\vGetApproval\x12#.siros.daemon.v1.GetApprovalRequest\x1a$.siros.daemon.v1.GetApprovalResponseB?Z=github.com/siros-io/go-siros-cli/api/proto/daemon/v1;daemonv1b\x06proto3"

var (
	file_api_proto_daemon_v1_wallet_proto_rawDescOnce sync.Once
	file_api_proto_daemon_v1_wallet_proto_rawDescData []byte
)

func file_api_proto_daemon_v1_wallet_proto_rawDescGZIP() []byte {
	file_api_proto_daemon_v1_wallet_proto_rawDescOnce.Do(func() {
		file_api_proto_daemon_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_daemon_v1_wallet_proto_rawDesc), len(file_api_proto_daemon_v1_wallet_proto_rawDesc)))
	})
	return file_api_proto_daemon_v1_wallet_proto_rawDescData
}

var file_api_proto_daemon_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_daemon_v1_wallet_proto_goTypes = []any{
	(*StatusRequest)(nil),             // 0: siros.daemon.v1.StatusRequest
	(*StatusResponse)(nil),            // 1: siros.daemon.v1.StatusResponse
	(*UnlockWithPRFRequest)(nil),      // 2: siros.daemon.v1.UnlockWithPRFRequest
	(*UnlockWithPasswordRequest)(nil), // 3: siros.daemon.v1.UnlockWithPasswordRequest
	(*UnlockResponse)(nil),            // 4: siros.daemon.v1.UnlockResponse
	(*LockRequest)(nil),               // 5: siros.daemon.v1.LockRequest
	(*LockResponse)(nil),              // 6: siros.daemon.v1.LockResponse
	(*SignJWTRequest)(nil),            // 7: siros.daemon.v1.SignJWTRequest
	(*SignJWTResponse)(nil),           // 8: siros.daemon.v1.SignJWTResponse
	(*SignRequest)(nil),               // 9: siros.daemon.v1.SignRequest
	(*SignResponse)(nil),              // 10: siros.daemon.v1.SignResponse
	(*ListKeysRequest)(nil),           // 11: siros.daemon.v1.ListKeysRequest
	(*KeyInfo)(nil),                   // 12: siros.daemon.v1.KeyInfo
	(*ListKeysResponse)(nil),          // 13: siros.daemon.v1.ListKeysResponse
	(*GetApprovalRequest)(nil),        // 14: siros.daemon.v1.GetApprovalRequest
	(*GetApprovalResponse)(nil),       // 15: siros.daemon.v1.GetApprovalResponse
	nil,                               // 16: siros.daemon.v1.SignJWTRequest.HeadersEntry
}
var file_api_proto_daemon_v1_wallet_proto_depIdxs = []int32{
	16, // 0: siros.daemon.v1.SignJWTRequest.headers:type_name -> siros.daemon.v1.SignJWTRequest.HeadersEntry
	12, // 1: siros.daemon.v1.ListKeysResponse.keys:type_name -> siros.daemon.v1.KeyInfo
	0,  // 2: siros.daemon.v1.WalletDaemon.Status:input_type -> siros.daemon.v1.StatusRequest
	2,  // 3: siros.daemon.v1.WalletDaemon.UnlockWithPRF:input_type -> siros.daemon.v1.UnlockWithPRFRequest
	3,  // 4: siros.daemon.v1.WalletDaemon.UnlockWithPassword:input_type -> siros.daemon.v1.UnlockWithPasswordRequest
	5,  // 5: siros.daemon.v1.WalletDaemon.Lock:input_type -> siros.daemon.v1.LockRequest
	7,  // 6: siros.daemon.v1.WalletDaemon.SignJWT:input_type -> siros.daemon.v1.SignJWTRequest
	9,  // 7: siros.daemon.v1.WalletDaemon.Sign:input_type -> siros.daemon.v1.SignRequest
	11, // 8: siros.daemon.v1.WalletDaemon.ListKeys:input_type -> siros.daemon.v1.ListKeysRequest
	14, // 9: siros.daemon.v1.WalletDaemon.GetApproval:input_type -> siros.daemon.v1.GetApprovalRequest
	1,  // 10: siros.daemon.v1.WalletDaemon.Status:output_type -> siros.daemon.v1.StatusResponse
	4,  // 11: siros.daemon.v1.WalletDaemon.UnlockWithPRF:output_type -> siros.daemon.v1.UnlockResponse
	4,  // 12: siros.daemon.v1.WalletDaemon.UnlockWithPassword:output_type -> siros.daemon.v1.UnlockResponse
	6,  // 13: siros.daemon.v1.WalletDaemon.Lock:output_type -> siros.daemon.v1.LockResponse
	8,  // 14: siros.daemon.v1.WalletDaemon.SignJWT:output_type -> siros.daemon.v1.SignJWTResponse
	10, // 15: siros.daemon.v1.WalletDaemon.Sign:output_type -> siros.daemon.v1.SignResponse
	13, // 16: siros.daemon.v1.WalletDaemon.ListKeys:output_type -> siros.daemon.v1.ListKeysResponse
	15, // 17: siros.daemon.v1.WalletDaemon.GetApproval:output_type -> siros.daemon.v1.GetApprovalResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_daemon_v1_wallet_proto_init() }
func file_api_proto_daemon_v1_wallet_proto_init() {
	if File_api_proto_daemon_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_daemon_v1_wallet_proto_rawDesc), len(file_api_proto_daemon_v1_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_daemon_v1_wallet_proto_goTypes,
		DependencyIndexes: file_api_proto_daemon_v1_wallet_proto_depIdxs,
		MessageInfos:      file_api_proto_daemon_v1_wallet_proto_msgTypes,
	}.Build()
	File_api_proto_daemon_v1_wallet_proto = out.File
	file_api_proto_daemon_v1_wallet_proto_goTypes = nil
	file_api_proto_daemon_v1_wallet_proto_depIdxs = nil
}
