// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/daemon/v1/wallet.proto

package daemonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletDaemon_Status_FullMethodName             = "/siros.daemon.v1.WalletDaemon/Status"
	WalletDaemon_UnlockWithPRF_FullMethodName      = "/siros.daemon.v1.WalletDaemon/UnlockWithPRF"
	WalletDaemon_UnlockWithPassword_FullMethodName = "/siros.daemon.v1.WalletDaemon/UnlockWithPassword"
	WalletDaemon_Lock_FullMethodName               = "/siros.daemon.v1.WalletDaemon/Lock"
	WalletDaemon_SignJWT_FullMethodName            = "/siros.daemon.v1.WalletDaemon/SignJWT"
	WalletDaemon_Sign_FullMethodName               = "/siros.daemon.v1.WalletDaemon/Sign"
	WalletDaemon_ListKeys_FullMethodName           = "/siros.daemon.v1.WalletDaemon/ListKeys"
	WalletDaemon_GetApproval_FullMethodName        = "/siros.daemon.v1.WalletDaemon/GetApproval"
)

// WalletDaemonClient is the client API for WalletDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletDaemon provides wallet operations over IPC.
type WalletDaemonClient interface {
	// Status returns the current daemon status.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// UnlockWithPRF unlocks the wallet using FIDO2 PRF.
	UnlockWithPRF(ctx context.Context, in *UnlockWithPRFRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	// UnlockWithPassword unlocks the wallet using a password.
	UnlockWithPassword(ctx context.Context, in *UnlockWithPasswordRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	// Lock locks the wallet.
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	// SignJWT signs a JWT with the specified key and claims.
	SignJWT(ctx context.Context, in *SignJWTRequest, opts ...grpc.CallOption) (*SignJWTResponse, error)
	// Sign performs a raw signature operation.
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	// ListKeys returns all available keys.
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// GetApproval requests user approval for an operation (MCP flow).
	GetApproval(ctx context.Context, in *GetApprovalRequest, opts ...grpc.CallOption) (*GetApprovalResponse, error)
}

type walletDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletDaemonClient(cc grpc.ClientConnInterface) WalletDaemonClient {
	return &walletDaemonClient{cc}
}

func (c *walletDaemonClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) UnlockWithPRF(ctx context.Context, in *UnlockWithPRFRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_UnlockWithPRF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) UnlockWithPassword(ctx context.Context, in *UnlockWithPasswordRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_UnlockWithPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_Lock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) SignJWT(ctx context.Context, in *SignJWTRequest, opts ...grpc.CallOption) (*SignJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignJWTResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_SignJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonClient) GetApproval(ctx context.Context, in *GetApprovalRequest, opts ...grpc.CallOption) (*GetApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApprovalResponse)
	err := c.cc.Invoke(ctx, WalletDaemon_GetApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletDaemonServer is the server API for WalletDaemon service.
// All implementations must embed UnimplementedWalletDaemonServer
// for forward compatibility.
//
// WalletDaemon provides wallet operations over IPC.
type WalletDaemonServer interface {
	// Status returns the current daemon status.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// UnlockWithPRF unlocks the wallet using FIDO2 PRF.
	UnlockWithPRF(context.Context, *UnlockWithPRFRequest) (*UnlockResponse, error)
	// UnlockWithPassword unlocks the wallet using a password.
	UnlockWithPassword(context.Context, *UnlockWithPasswordRequest) (*UnlockResponse, error)
	// Lock locks the wallet.
	Lock(context.Context, *LockRequest) (*LockResponse, error)
	// SignJWT signs a JWT with the specified key and claims.
	SignJWT(context.Context, *SignJWTRequest) (*SignJWTResponse, error)
	// Sign performs a raw signature operation.
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	// ListKeys returns all available keys.
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// GetApproval requests user approval for an operation (MCP flow).
	GetApproval(context.Context, *GetApprovalRequest) (*GetApprovalResponse, error)
	mustEmbedUnimplementedWalletDaemonServer()
}

// UnimplementedWalletDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletDaemonServer struct{}

func (UnimplementedWalletDaemonServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedWalletDaemonServer) UnlockWithPRF(context.Context, *UnlockWithPRFRequest) (*UnlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockWithPRF not implemented")
}
func (UnimplementedWalletDaemonServer) UnlockWithPassword(context.Context, *UnlockWithPasswordRequest) (*UnlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockWithPassword not implemented")
}
func (UnimplementedWalletDaemonServer) Lock(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedWalletDaemonServer) SignJWT(context.Context, *SignJWTRequest) (*SignJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignJWT not implemented")
}
func (UnimplementedWalletDaemonServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedWalletDaemonServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedWalletDaemonServer) GetApproval(context.Context, *GetApprovalRequest) (*GetApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApproval not implemented")
}
func (UnimplementedWalletDaemonServer) mustEmbedUnimplementedWalletDaemonServer() {}
func (UnimplementedWalletDaemonServer) testEmbeddedByValue()                      {}

// UnsafeWalletDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletDaemonServer will
// result in compilation errors.
type UnsafeWalletDaemonServer interface {
	mustEmbedUnimplementedWalletDaemonServer()
}

func RegisterWalletDaemonServer(s grpc.ServiceRegistrar, srv WalletDaemonServer) {
	// If the following call panics, it indicates UnimplementedWalletDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletDaemon_ServiceDesc, srv)
}

func _WalletDaemon_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_UnlockWithPRF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockWithPRFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).UnlockWithPRF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_UnlockWithPRF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).UnlockWithPRF(ctx, req.(*UnlockWithPRFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_UnlockWithPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockWithPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).UnlockWithPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_UnlockWithPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).UnlockWithPassword(ctx, req.(*UnlockWithPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_Lock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_SignJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).SignJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_SignJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).SignJWT(ctx, req.(*SignJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemon_GetApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServer).GetApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletDaemon_GetApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServer).GetApproval(ctx, req.(*GetApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletDaemon_ServiceDesc is the grpc.ServiceDesc for WalletDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "siros.daemon.v1.WalletDaemon",
	HandlerType: (*WalletDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _WalletDaemon_Status_Handler,
		},
		{
			MethodName: "UnlockWithPRF",
			Handler:    _WalletDaemon_UnlockWithPRF_Handler,
		},
		{
			MethodName: "UnlockWithPassword",
			Handler:    _WalletDaemon_UnlockWithPassword_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _WalletDaemon_Lock_Handler,
		},
		{
			MethodName: "SignJWT",
			Handler:    _WalletDaemon_SignJWT_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _WalletDaemon_Sign_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _WalletDaemon_ListKeys_Handler,
		},
		{
			MethodName: "GetApproval",
			Handler:    _WalletDaemon_GetApproval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/daemon/v1/wallet.proto",
}
