#!/bin/sh
set -e
# Automatically added by dh_installsystemduser/13.24.1ubuntu2
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'wallet-cli-daemon.service' 'wallet-cli-daemon.socket' >/dev/null || true
	fi
fi
# End automatically added section
